steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/octopus-dev-309403/cloud-run-source-deploy/socialfi-agent', '.' ]
images:
- 'us-central1-docker.pkg.dev/octopus-dev-309403/cloud-run-source-deploy/socialfi-agent'
timeout: 1800s
options:
  machineType: 'E2_HIGHCPU_32'

# gcloud builds submit --config=cloudbuild.yaml
